name: Demo

on: [push]

workflow_dispatch:
  inputs:
    environment:
      description: 'Environment to deploy to'
      type: environment
      required: true


jobs:
   hello:
    name: "Say hello"
    runs-on:  ubuntu-latest
    steps:
      - name: Say hello
        run: echo Hello
    
    
   

